version: '3.8'

networks:
    app-network:
        driver: bridge

volumes:
    app-modules:
        driver: local

services:

    api:
        env_file: .env
        container_name: node-api
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./api/Dockerfile
            args:
                API_PORT: ${API_PORT}
                NGINX_PORT: ${NGINX_PORT}
        ports:
            - '${API_PORT}:3000'
        volumes:
            - ./src:/app
            - 'app-modules:/app/node_modules'
        networks:
            - app-network

    nginx:
        env_file: .env
        container_name: node-nginx
        restart: unless-stopped
        tty: true
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - '${NGINX_PORT}:80'
        volumes:
            - ./src:/app
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            - api
