version: "3.7"

networks:
  lan:

volumes:
  db-data:
    driver: local

services:
  nginx:
    image: nginx:stable-alpine
    container_name: phpapp-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./docker_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - lan

  db:
    image: mysql:5.7.29
    container_name: phpapp-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: phpapp
      MYSQL_USER: phpapp
      MYSQL_PASSWORD: phpapp
      MYSQL_ROOT_PASSWORD: phpapp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lan

  php:
    build:
      context: ./
      dockerfile: php.dockerfile
      args:
        user: php
        uid: 1000
        environment: dev
    container_name: phpapp-php
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "9000:9000"
    networks:
      - lan
